// Generated by scripts/upload-blobs.mjs — do not edit by hand.
export const blobAssets = {
  "cta-bg.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/cta-bg.png",
  "cta-ipad-screen.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/cta-ipad-screen.png",
  "cta-ipad.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/cta-ipad.png",
  "feature-inventory.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/feature-inventory.png",
  "feature-kds.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/feature-kds.png",
  "feature-sales.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/feature-sales.png",
  "feature-settings.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/feature-settings.png",
  "feature-tables.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/feature-tables.png",
  "hero-ipad-screen.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/hero-ipad-screen.png",
  "solution-cafe.png": "https://udg4m9bnyz7haae7.public.blob.vercel-storage.com/figma-assets/solution-cafe.png"
} as const;

export type BlobAsset = keyof typeof blobAssets;
