import { InfoPageHero } from "@/components/sections/InfoPageHero";
import { InfoPageBody } from "@/components/sections/InfoPageBody";

export const metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of Mise POS software and services.",
};

export default function TermsPage() {
  return (
    <>
      <InfoPageHero
        eyebrow="Legal"
        title={<>Terms of Service</>}
        description="The rules of the road for using Mise — billing, uptime, data ownership, and what happens if things go sideways."
      />
      <InfoPageBody
        lastUpdated="01 May 2026"
        intro={
          <p>
            By creating an Mise account or running an Mise terminal you
            agree to these terms. They are written in plain English on purpose
            — the long-form Master Services Agreement is available on request
            for Enterprise customers.
          </p>
        }
        blocks={[
          {
            heading: "The service",
            body: (
              <p>
                Mise provides cloud-based point-of-sale software, a kitchen
                display system, and back-office reporting for food and
                beverage operators. Hardware is sold or rented separately.
              </p>
            ),
          },
          {
            heading: "Billing and trials",
            body: (
              <>
                <p>
                  Plans are billed monthly or annually in advance. Annual plans
                  receive a 20% discount. You can cancel from the billing
                  panel at any time — there is no minimum term, and no
                  per-terminal or per-transaction fees.
                </p>
                <p>
                  The 14-day free trial does not require a credit card and
                  converts to your selected plan only on confirmation.
                </p>
              </>
            ),
          },
          {
            heading: "Uptime",
            body: (
              <p>
                We commit to 99.9% monthly uptime for the cloud back office.
                The terminal continues to take orders and print kitchen
                tickets offline if your internet drops — see the FAQ for how
                offline sync works. Service credits for downtime are documented
                in our SLA.
              </p>
            ),
          },
          {
            heading: "Your data",
            body: (
              <p>
                Operational data generated by your use of Mise belongs to
                you. Full CSV export is one click; API access ships with
                Enterprise plans. We do not hold your data hostage if you
                decide to leave.
              </p>
            ),
          },
          {
            heading: "Acceptable use",
            body: (
              <p>
                You agree not to use Mise to facilitate illegal activity, to
                reverse-engineer the service, or to resell access to your
                account. Outlet operators are responsible for tax compliance
                in their jurisdiction.
              </p>
            ),
          },
          {
            heading: "Liability",
            body: (
              <p>
                To the maximum extent permitted by law, our aggregate
                liability is limited to the fees you paid in the twelve months
                preceding the event. Nothing in these terms excludes
                non-excludable rights under the Australian Consumer Law.
              </p>
            ),
          },
          {
            heading: "Contact",
            body: (
              <p>
                Questions? Email legal@mise.app. Notices may be sent to
                Mise Pty Ltd, Level 1, 12 Sample St, Sydney NSW 2000.
              </p>
            ),
          },
        ]}
      />
    </>
  );
}
