import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { put } from "@vercel/blob";

const ASSETS_DIR = "public/figma-assets";
const MANIFEST_PATH = "src/lib/blob-manifest.ts";

async function main() {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  if (!token) {
    console.error("Missing BLOB_READ_WRITE_TOKEN. Run: vercel env pull");
    process.exit(1);
  }

  const files = await readdir(ASSETS_DIR);
  const pngs = files.filter((f) => f.endsWith(".png"));
  console.log(`Uploading ${pngs.length} files…`);

  const results = await Promise.all(
    pngs.map(async (filename) => {
      const buf = await readFile(join(ASSETS_DIR, filename));
      const res = await put(`figma-assets/${filename}`, buf, {
        access: "public",
        contentType: "image/png",
        addRandomSuffix: false,
        allowOverwrite: true,
        cacheControlMaxAge: 60 * 60 * 24 * 365,
        token,
      });
      console.log(`  ✓ ${filename} → ${res.url}`);
      return [filename, res.url];
    }),
  );

  const manifest = Object.fromEntries(results);
  const tsContent =
    `// Generated by scripts/upload-blobs.mjs — do not edit by hand.\n` +
    `export const blobAssets = ${JSON.stringify(manifest, null, 2)} as const;\n\n` +
    `export type BlobAsset = keyof typeof blobAssets;\n`;

  await writeFile(MANIFEST_PATH, tsContent);
  console.log(`\nManifest written to ${MANIFEST_PATH}`);
}

main().catch((err) => {
  console.error("Upload failed:", err);
  process.exit(1);
});
