import { InfoPageHero } from "@/components/sections/InfoPageHero";
import { InfoPageBody } from "@/components/sections/InfoPageBody";

export const metadata = {
  title: "Privacy Policy",
  description:
    "How Mise collects, uses, and protects data from F&B operators and their customers.",
};

export default function PrivacyPage() {
  return (
    <>
      <InfoPageHero
        eyebrow="Legal"
        title="Privacy Policy"
        description="The plain-English version of how we handle your data — what we collect, why, and what you can do about it."
      />
      <InfoPageBody
        lastUpdated="01 May 2026"
        intro={
          <p>
            Mise Pty Ltd (&quot;Mise&quot;, &quot;we&quot;) is an Australian
            company headquartered in Sydney. This policy explains what we do
            with personal information collected through mise.app, our
            terminals, and our back-office dashboards. It is written to comply
            with the Australian Privacy Principles (APPs) under the Privacy Act
            1988 (Cth), and the GDPR where applicable.
          </p>
        }
        blocks={[
          {
            heading: "What we collect",
            body: (
              <>
                <p>
                  Operator data — business name, ABN, contact details, billing
                  information, and login credentials for users you create on
                  your account.
                </p>
                <p>
                  Operational data — orders, payments, inventory movements, and
                  staff activity generated by your use of Mise. This data is
                  owned by you; we are the processor.
                </p>
                <p>
                  End-customer data — when you choose to enable membership,
                  loyalty, or receipts-by-email, we store the minimum customer
                  identifiers required to deliver those features.
                </p>
              </>
            ),
          },
          {
            heading: "Why we collect it",
            body: (
              <>
                <p>
                  To run the service, settle payments, send transactional
                  emails, and produce the reports your account relies on. We do
                  not sell operator or end-customer data to third parties.
                </p>
              </>
            ),
          },
          {
            heading: "Where it lives",
            body: (
              <>
                <p>
                  Primary storage is in AWS ap-southeast-2 (Sydney). Encrypted
                  backups are held in ap-southeast-4 (Melbourne). Subprocessors
                  used for email delivery, error tracking, and analytics are
                  listed in our Data Processing Addendum, available on request.
                </p>
              </>
            ),
          },
          {
            heading: "Your rights",
            body: (
              <>
                <p>
                  You can request access, correction, or deletion of your
                  personal data at any time by emailing
                  privacy@mise.app. Operator account data is exportable to
                  CSV with one click.
                </p>
              </>
            ),
          },
          {
            heading: "Contact",
            body: (
              <p>
                Questions or complaints? Email privacy@mise.app or write to
                the Privacy Officer, Mise Pty Ltd, Level 1, 12 Sample St,
                Sydney NSW 2000.
              </p>
            ),
          },
        ]}
      />
    </>
  );
}
